import { sql } from 'drizzle-orm';
import { boolean, check, date, index, integer, jsonb, pgTable, primaryKey, smallint, text, timestamp, unique, uuid } from 'drizzle-orm/pg-core';
import { id, timestamps } from './_common';
import { asset } from './assets-risks';
import { person } from './core';
import {
  biaDimensionEnum,
  biaHorizonEnum,
  biaStatusEnum,
  incidentCategoryEnum,
  incidentSourceEnum,
  incidentStatusEnum,
  planStatusEnum,
  playbookScenarioEnum,
  playbookStatusEnum,
  rcaMethodEnum,
  reportingRegimeEnum,
  severityEnum,
} from './enums';
import { tenant, user } from './platform';

// G · Betrieb, Vorfälle & Business Continuity ------------------------------------------------------

const tenantRef = () =>
  uuid('tenant_id')
    .notNull()
    .references(() => tenant.id, { onDelete: 'cascade' });

export const businessProcess = pgTable(
  'business_process',
  {
    id: id(),
    tenantId: tenantRef(),
    name: text('name').notNull(),
    department: text('department'),
    description: text('description'),
    ownerPersonId: uuid('owner_person_id').references(() => person.id, { onDelete: 'set null' }),
    tier: smallint('tier'),
    ...timestamps,
  },
  (t) => [index('process_tenant_idx').on(t.tenantId, t.tier), check('process_tier_chk', sql`${t.tier} IS NULL OR ${t.tier} BETWEEN 1 AND 3`)],
);

export const playbook = pgTable(
  'playbook',
  {
    id: id(),
    tenantId: tenantRef(),
    title: text('title').notNull(),
    description: text('description'),
    scenario: playbookScenarioEnum('scenario').notNull().default('custom'),
    assetId: uuid('asset_id').references(() => asset.id, { onDelete: 'set null' }),
    processId: uuid('process_id').references(() => businessProcess.id, { onDelete: 'set null' }),
    status: playbookStatusEnum('status').notNull().default('draft'),
    autoGenerated: boolean('auto_generated').notNull().default(false),
    ...timestamps,
  },
  (t) => [index('playbook_tenant_idx').on(t.tenantId, t.status)],
);

export const playbookStep = pgTable(
  'playbook_step',
  {
    id: id(),
    tenantId: tenantRef(),
    playbookId: uuid('playbook_id')
      .notNull()
      .references(() => playbook.id, { onDelete: 'cascade' }),
    seq: smallint('seq').notNull(),
    title: text('title').notNull(),
    instruction: text('instruction'),
    roleHint: text('role_hint'),
    contactPersonId: uuid('contact_person_id').references(() => person.id, { onDelete: 'set null' }),
  },
  (t) => [unique('playbook_step_uq').on(t.playbookId, t.seq)],
);

export const incident = pgTable(
  'incident',
  {
    id: id(),
    tenantId: tenantRef(),
    refNo: text('ref_no').notNull(),
    title: text('title').notNull(),
    description: text('description'),
    category: incidentCategoryEnum('category').notNull().default('other'),
    severity: severityEnum('severity').notNull().default('medium'),
    status: incidentStatusEnum('status').notNull().default('new'),
    detectedAt: timestamp('detected_at', { withTimezone: true }).notNull().defaultNow(),
    occurredAt: timestamp('occurred_at', { withTimezone: true }),
    reportedByUserId: uuid('reported_by_user_id').references(() => user.id),
    handlerPersonId: uuid('handler_person_id').references(() => person.id, { onDelete: 'set null' }),
    source: incidentSourceEnum('source').notNull().default('manual'),
    externalRef: text('external_ref'),
    isPersonalDataBreach: boolean('is_personal_data_breach').notNull().default(false),
    breachConfirmedAt: timestamp('breach_confirmed_at', { withTimezone: true }),
    affectedPersons: integer('affected_persons'),
    nis2Relevant: boolean('nis2_relevant').notNull().default(false),
    nis2SignificantAt: timestamp('nis2_significant_at', { withTimezone: true }),
    crossBorder: boolean('cross_border').notNull().default(false),
    playbookId: uuid('playbook_id').references(() => playbook.id, { onDelete: 'set null' }),
    resolvedAt: timestamp('resolved_at', { withTimezone: true }),
    closedAt: timestamp('closed_at', { withTimezone: true }),
    ...timestamps,
  },
  (t) => [
    unique('incident_tenant_ref_uq').on(t.tenantId, t.refNo),
    index('incident_tenant_status_idx').on(t.tenantId, t.status, t.severity),
    index('incident_detected_idx').on(t.tenantId, t.detectedAt),
  ],
);

export const incidentAsset = pgTable(
  'incident_asset',
  {
    tenantId: tenantRef(),
    incidentId: uuid('incident_id')
      .notNull()
      .references(() => incident.id, { onDelete: 'cascade' }),
    assetId: uuid('asset_id')
      .notNull()
      .references(() => asset.id, { onDelete: 'cascade' }),
  },
  (t) => [primaryKey({ columns: [t.incidentId, t.assetId] }), index('incident_asset_asset_idx').on(t.tenantId, t.assetId)],
);

export const incidentTimeline = pgTable(
  'incident_timeline',
  {
    id: id(),
    tenantId: tenantRef(),
    incidentId: uuid('incident_id')
      .notNull()
      .references(() => incident.id, { onDelete: 'cascade' }),
    at: timestamp('at', { withTimezone: true }).notNull().defaultNow(),
    actorUserId: uuid('actor_user_id').references(() => user.id),
    kind: text('kind').notNull(),
    text: text('text').notNull(),
  },
  (t) => [index('incident_timeline_idx').on(t.incidentId, t.at)],
);

/** Meldefristen — je Vorfall und Regime eine Zeile; erzeugt vom Backend bei Bestätigung. */
export const reportingObligation = pgTable(
  'reporting_obligation',
  {
    id: id(),
    tenantId: tenantRef(),
    incidentId: uuid('incident_id')
      .notNull()
      .references(() => incident.id, { onDelete: 'cascade' }),
    regime: reportingRegimeEnum('regime').notNull(),
    dueAt: timestamp('due_at', { withTimezone: true }),
    fulfilledAt: timestamp('fulfilled_at', { withTimezone: true }),
    authority: text('authority'),
    reference: text('reference'),
    note: text('note'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    unique('reporting_obligation_uq').on(t.incidentId, t.regime),
    index('reporting_obligation_open_idx').on(t.tenantId, t.dueAt).where(sql`fulfilled_at IS NULL`),
  ],
);

export const rootCauseAnalysis = pgTable(
  'root_cause_analysis',
  {
    id: id(),
    tenantId: tenantRef(),
    incidentId: uuid('incident_id')
      .notNull()
      .references(() => incident.id, { onDelete: 'cascade' })
      .unique(),
    method: rcaMethodEnum('method').notNull().default('5why'),
    problemStatement: text('problem_statement'),
    analysis: jsonb('analysis').notNull().default(sql`'{}'::jsonb`),
    rootCause: text('root_cause'),
    conclusions: text('conclusions'),
    performedByUserId: uuid('performed_by_user_id').references(() => user.id),
    performedAt: timestamp('performed_at', { withTimezone: true }),
    ...timestamps,
  },
);

export const incidentPlaybookStep = pgTable(
  'incident_playbook_step',
  {
    tenantId: tenantRef(),
    incidentId: uuid('incident_id')
      .notNull()
      .references(() => incident.id, { onDelete: 'cascade' }),
    stepId: uuid('step_id')
      .notNull()
      .references(() => playbookStep.id, { onDelete: 'cascade' }),
    doneAt: timestamp('done_at', { withTimezone: true }),
    doneByUserId: uuid('done_by_user_id').references(() => user.id),
    note: text('note'),
  },
  (t) => [primaryKey({ columns: [t.incidentId, t.stepId] })],
);

// BIA / BCP -------------------------------------------------------------------------------------------

export const bia = pgTable(
  'bia',
  {
    id: id(),
    tenantId: tenantRef(),
    processId: uuid('process_id')
      .notNull()
      .references(() => businessProcess.id, { onDelete: 'cascade' }),
    mtpdHours: integer('mtpd_hours'),
    rtoHours: integer('rto_hours'),
    rpoHours: integer('rpo_hours'),
    mbco: text('mbco'),
    status: biaStatusEnum('status').notNull().default('draft'),
    approvedByUserId: uuid('approved_by_user_id').references(() => user.id),
    approvedAt: timestamp('approved_at', { withTimezone: true }),
    ...timestamps,
  },
  (t) => [
    index('bia_tenant_idx').on(t.tenantId, t.processId),
    check('bia_rto_chk', sql`${t.mtpdHours} IS NULL OR ${t.rtoHours} IS NULL OR ${t.rtoHours} <= ${t.mtpdHours}`),
  ],
);

export const biaImpact = pgTable(
  'bia_impact',
  {
    biaId: uuid('bia_id')
      .notNull()
      .references(() => bia.id, { onDelete: 'cascade' }),
    dimension: biaDimensionEnum('dimension').notNull(),
    horizon: biaHorizonEnum('horizon').notNull(),
    score: smallint('score').notNull(),
  },
  (t) => [primaryKey({ columns: [t.biaId, t.dimension, t.horizon] }), check('bia_impact_score_chk', sql`${t.score} BETWEEN 0 AND 4`)],
);

export const biaResource = pgTable(
  'bia_resource',
  {
    biaId: uuid('bia_id')
      .notNull()
      .references(() => bia.id, { onDelete: 'cascade' }),
    assetId: uuid('asset_id')
      .notNull()
      .references(() => asset.id, { onDelete: 'cascade' }),
    criticality: smallint('criticality'),
  },
  (t) => [primaryKey({ columns: [t.biaId, t.assetId] })],
);

export const continuityPlan = pgTable(
  'continuity_plan',
  {
    id: id(),
    tenantId: tenantRef(),
    biaId: uuid('bia_id')
      .notNull()
      .references(() => bia.id, { onDelete: 'cascade' }),
    title: text('title').notNull(),
    activationCriteria: text('activation_criteria'),
    strategy: text('strategy'),
    status: planStatusEnum('status').notNull().default('draft'),
    /** Übungsintervall; bestimmt nach einer Übung die nächste Fälligkeit. */
    testIntervalMonths: smallint('test_interval_months').notNull().default(12),
    lastTestAt: date('last_test_at'),
    nextTestAt: date('next_test_at'),
    ...timestamps,
  },
  (t) => [index('continuity_plan_tenant_idx').on(t.tenantId, t.nextTestAt)],
);

export const continuityPlanStep = pgTable(
  'continuity_plan_step',
  {
    id: id(),
    planId: uuid('plan_id')
      .notNull()
      .references(() => continuityPlan.id, { onDelete: 'cascade' }),
    seq: smallint('seq').notNull(),
    phase: text('phase'),
    title: text('title').notNull(),
    instruction: text('instruction'),
    responsiblePersonId: uuid('responsible_person_id').references(() => person.id, { onDelete: 'set null' }),
  },
  (t) => [unique('continuity_plan_step_uq').on(t.planId, t.seq)],
);

export const bcExercise = pgTable(
  'bc_exercise',
  {
    id: id(),
    tenantId: tenantRef(),
    planId: uuid('plan_id')
      .notNull()
      .references(() => continuityPlan.id, { onDelete: 'cascade' }),
    heldAt: date('held_at').notNull(),
    kind: text('kind').notNull().default('tabletop'),
    result: text('result'),
    lessonsLearned: text('lessons_learned'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('bc_exercise_plan_idx').on(t.planId, t.heldAt)],
);
